services:
  valkey:
    image: valkey/valkey:8.0
    container_name: blog-valkey
    command: valkey-server --requirepass valkeyPassword123
    ports:
      - '6379:6379'
    volumes:
      - valkey_data:/data
    restart: always

  postgres:
    image: postgres:17
    container_name: blog-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  valkey_data:
